### ISSUE TITLE
Crash with 1.4

### ISSUE THREAD

**Issue by hoelzi** [maxvollmer/DeepWoodsMod#7]
This crashes my game on 1.4:

	System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei StardewValley.TerrainFeatures.FruitTree.dayUpdate(GameLocation environment, Vector2 tileLocation) in C:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\TerrainFeatures\FruitTree.cs:Zeile 383.
   bei StardewValley.GameLocation.DayUpdate(Int32 dayOfMonth) in C:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:Zeile 3136.
   bei DeepWoodsMod.DeepWoods.DayUpdate(Int32 dayOfMonth) in C:\SDV_Modding\ModUpdates\DeepWoodsMod\DeepWoodsMod\DeepWoods.cs:Zeile 588.
   bei StardewValley.Game1._newDayAfterFade() in C:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:Zeile 7497.
   bei StardewValley.Game1.<>c.<newDayAfterFade>b__606_1() in C:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:Zeile 6917.
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by maxvollmer** [comment]
DeepWoods is not compatible with SDV 1.4. You are probably running the unofficial patch by Mizzion. I cannot offer support for that version. Also, if reporting bugs, please including the full SMAPI log (upload it to https://smapi.io/log/), a stacktrace alone without the full log isn't enough to debug problems. I also prefer bug reports on the official mod page, not here. Thank you!
